version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: locationdb
      POSTGRES_USER: ${DB_USER:-locuser}
      POSTGRES_PASSWORD: ${DB_PASS:-locpass}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - locnet
  web:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER:-locuser}
      DB_PASS: ${DB_PASS:-locpass}
    ports:
      - "8080:8080"
    networks:
      - locnet
volumes:
  db_data:
networks:
  locnet:
